image: node:latest  # Use a valid Docker image

before_script:
  - npm ci

pages:
  script:
    - npm run build
    - cp -r public/ .  # Make sure the "public" folder exists after the build
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
