image: node:latest  # Use the latest Node.js image

before_script:
  - npm ci  # Install dependencies

pages:
  script:
    - npm run build || echo "No build step, skipping..."
    - mkdir -p public
    - cp -r src/* public/  # Move all files to the 'public' folder
  artifacts:
    paths:
      - public  # GitLab Pages serves files from 'public'
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH  # Deploy only from the main branch
